apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-enterprise-starter-kit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-enterprise-starter-kit
  template:
    metadata:
      labels:
        app: nestjs-enterprise-starter-kit
    spec:
      containers:
        - name: nestjs-server
          image: REPLACE_WITH_IMAGE_TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: NODE_ENV
              value: 'production'

